#ifndef RS_ERROR_HPP
#define RS_ERROR_HPP

#define ERROR_SUCCESS 0

#define ERROR_INVALID_PARAM 1001
#define ERROR_INVALID_ACTION 1002
#define ERROR_SINGULAR_MATRIX 1003
#define ERROR_MATRIX_NOT_SQUARE 1004
#define ERROR_TOO_FEW_SHARDS 1005

#endif // ERROR_HPP
